package com.flutter_app_intents

import android.content.Context
import androidx.annotation.NonNull
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.common.MethodChannel.MethodCallHandler
import io.flutter.plugin.common.MethodChannel.Result

/**
 * FlutterAppIntentsPlugin
 *
 * Android implementation of the flutter_app_intents plugin.
 * Provides Google App Actions integration for voice commands via Google Assistant.
 *
 * Requires Android 7.1+ (API 25) for App Actions support.
 */
class FlutterAppIntentsPlugin : FlutterPlugin, MethodCallHandler {
    private lateinit var channel: MethodChannel
    private lateinit var context: Context

    // Store registered intent handlers
    private val intentHandlers = mutableMapOf<String, IntentHandler>()

    // Queue for intents received before Flutter is ready (cold start)
    private val pendingIntents = mutableListOf<PendingIntentData>()
    private var isFlutterReady = false

    companion object {
        lateinit var instance: FlutterAppIntentsPlugin
            private set
    }

    override fun onAttachedToEngine(@NonNull flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
        instance = this
        context = flutterPluginBinding.applicationContext
        channel = MethodChannel(flutterPluginBinding.binaryMessenger, "flutter_app_intents")
        channel.setMethodCallHandler(this)

        // Mark Flutter as ready and process any queued intents
        isFlutterReady = true
        processPendingIntents()
    }

    override fun onMethodCall(@NonNull call: MethodCall, @NonNull result: Result) {
        when (call.method) {
            "getApiLevel" -> getApiLevel(result)
            "registerIntent" -> registerIntent(call, result)
            "registerIntents" -> registerIntents(call, result)
            "unregisterIntent" -> unregisterIntent(call, result)
            "getRegisteredIntents" -> getRegisteredIntents(result)
            "updateShortcuts" -> updateShortcuts(result)
            "donateIntent" -> donateIntent(call, result)
            "donateIntentBatch" -> donateIntentBatch(call, result)
            else -> result.notImplemented()
        }
    }

    /**
     * Get the Android API level
     */
    private fun getApiLevel(result: Result) {
        result.success(android.os.Build.VERSION.SDK_INT)
    }

    override fun onDetachedFromEngine(@NonNull binding: FlutterPlugin.FlutterPluginBinding) {
        channel.setMethodCallHandler(null)
        isFlutterReady = false
    }

    /**
     * Register a single intent with the Android system
     *
     * Note: This validates that shortcuts.xml exists with a matching capability.
     * The shortcuts.xml file should be generated by running:
     * dart run flutter_app_intents:generate --platform=android
     */
    private fun registerIntent(call: MethodCall, result: Result) {
        val identifier = call.argument<String>("identifier")
        if (identifier == null) {
            result.error("INVALID_ARGS", "Missing identifier", null)
            return
        }

        val title = call.argument<String>("title")
        if (title == null) {
            result.error("INVALID_ARGS", "Missing title", null)
            return
        }

        try {
            // Validate that shortcuts.xml has a matching capability
            // (shortcuts.xml is generated by: dart run flutter_app_intents:generate)
            if (!shortcutExists(identifier)) {
                result.error(
                    "MISSING_SHORTCUT",
                    "No <capability> found in shortcuts.xml for '$identifier'. " +
                    "Run: dart run flutter_app_intents:generate --platform=android",
                    null
                )
                return
            }

            // Store handler mapping
            intentHandlers[identifier] = IntentHandler(identifier)

            result.success(true)
        } catch (e: Exception) {
            result.error("REGISTRATION_FAILED", e.message, null)
        }
    }

    /**
     * Register multiple intents
     */
    private fun registerIntents(call: MethodCall, result: Result) {
        val intents = call.argument<List<Map<String, Any>>>("intents")
        if (intents == null) {
            result.error("INVALID_ARGS", "Missing intents", null)
            return
        }

        try {
            for (intentMap in intents) {
                val identifier = intentMap["identifier"] as? String
                if (identifier != null && shortcutExists(identifier)) {
                    intentHandlers[identifier] = IntentHandler(identifier)
                }
            }

            result.success(true)
        } catch (e: Exception) {
            result.error("REGISTRATION_FAILED", e.message, null)
        }
    }

    /**
     * Unregister an intent
     */
    private fun unregisterIntent(call: MethodCall, result: Result) {
        val identifier = call.argument<String>("identifier")
        if (identifier == null) {
            result.error("INVALID_ARGS", "Missing identifier", null)
            return
        }

        intentHandlers.remove(identifier)
        result.success(true)
    }

    /**
     * Get all registered intents
     */
    private fun getRegisteredIntents(result: Result) {
        val intents = intentHandlers.keys.map { identifier ->
            mapOf("identifier" to identifier)
        }
        result.success(intents)
    }

    /**
     * Update shortcuts (placeholder - actual updating happens via shortcuts.xml)
     */
    private fun updateShortcuts(result: Result) {
        // On Android, shortcuts are defined in shortcuts.xml
        // This method is kept for API compatibility with iOS
        result.success(true)
    }

    /**
     * Donate an intent execution for ML learning
     */
    private fun donateIntent(call: MethodCall, result: Result) {
        // Android's App Actions handles usage tracking automatically
        // This method is kept for API compatibility with iOS
        result.success(true)
    }

    /**
     * Batch donate intents
     */
    private fun donateIntentBatch(call: MethodCall, result: Result) {
        // Android's App Actions handles usage tracking automatically
        // This method is kept for API compatibility with iOS
        result.success(true)
    }

    /**
     * Called when an App Action is triggered by Google Assistant
     * May be called before Flutter is ready (cold start)
     */
    fun handleIntentInvocation(
        identifier: String,
        parameters: Map<String, Any>
    ) {
        if (!isFlutterReady) {
            // Queue for later processing
            pendingIntents.add(
                PendingIntentData(
                    identifier = identifier,
                    params = parameters,
                    timestamp = System.currentTimeMillis()
                )
            )
            return
        }

        // Process immediately
        callFlutterHandler(identifier, parameters)
    }

    /**
     * Process any intents that were queued during cold start
     */
    private fun processPendingIntents() {
        pendingIntents.forEach { pending ->
            callFlutterHandler(pending.identifier, pending.params)
        }
        pendingIntents.clear()
    }

    /**
     * Call the Flutter handler for an intent
     */
    private fun callFlutterHandler(identifier: String, parameters: Map<String, Any>) {
        val args = mapOf(
            "identifier" to identifier,
            "parameters" to parameters
        )

        channel.invokeMethod("handleIntent", args)
    }

    /**
     * Check if a shortcut exists in shortcuts.xml
     *
     * This is a placeholder implementation. The actual shortcuts.xml
     * will be generated by the code generator.
     */
    private fun shortcutExists(identifier: String): Boolean {
        // TODO: Parse shortcuts.xml and verify capability exists
        // For now, assume shortcuts.xml is properly generated
        return true
    }

    /**
     * Data class for intent handler registration
     */
    data class IntentHandler(
        val identifier: String
    )

    /**
     * Data class for queued intents (cold start)
     */
    data class PendingIntentData(
        val identifier: String,
        val params: Map<String, Any>,
        val timestamp: Long
    )
}
