//
// AppShortcuts.swift
// Generated by flutter_app_intents code generator
//
// DO NOT EDIT - This file is auto-generated
// Run: dart run flutter_app_intents:app_intents_cli
//

import AppIntents
import Foundation
import flutter_app_intents

// MARK: - Error Handling

/// Error type for App Intent execution failures
enum IntentExecutionError: Error {
    case executionFailed
}

// MARK: - App Intent Definitions

@available(iOS 16.0, *)
struct OpenProfileIntent: AppIntent {
    static var title: LocalizedStringResource = "Open Profile"

    static var description: IntentDescription = IntentDescription("Navigate to user profile page")

    static var openAppWhenRun: Bool { true }

    @Parameter(title: "User ID")
    var userId: String?

    @MainActor
    func perform() async throws -> some IntentResult {
        // Call into Flutter via plugin
        var parameters: [String: Any] = [:]
        if let userId = userId {
            parameters["userId"] = userId
        }

        let result = await FlutterAppIntentsPlugin.shared.handleIntentInvocation(
            identifier: "open_profile",
            parameters: parameters
        )

        if let success = result["success"] as? Bool, success {
            return .result()
        } else {
            throw IntentExecutionError.executionFailed
        }
    }
}

@available(iOS 16.0, *)
struct OpenChatIntent: AppIntent {
    static var title: LocalizedStringResource = "Open Chat"

    static var description: IntentDescription = IntentDescription("Open chat with a contact")

    static var openAppWhenRun: Bool { true }

    @Parameter(title: "Contact Name")
    var contactName: String

    @MainActor
    func perform() async throws -> some IntentResult {
        // Call into Flutter via plugin
        var parameters: [String: Any] = [:]
        parameters["contactName"] = contactName

        let result = await FlutterAppIntentsPlugin.shared.handleIntentInvocation(
            identifier: "open_chat",
            parameters: parameters
        )

        if let success = result["success"] as? Bool, success {
            return .result()
        } else {
            throw IntentExecutionError.executionFailed
        }
    }
}

@available(iOS 16.0, *)
struct SearchContentIntent: AppIntent {
    static var title: LocalizedStringResource = "Search Content"

    static var description: IntentDescription = IntentDescription("Search for content in the app")

    static var openAppWhenRun: Bool { true }

    @Parameter(title: "Search Query")
    var query: String

    @MainActor
    func perform() async throws -> some IntentResult {
        // Call into Flutter via plugin
        var parameters: [String: Any] = [:]
        parameters["query"] = query

        let result = await FlutterAppIntentsPlugin.shared.handleIntentInvocation(
            identifier: "search_content",
            parameters: parameters
        )

        if let success = result["success"] as? Bool, success {
            return .result()
        } else {
            throw IntentExecutionError.executionFailed
        }
    }
}

@available(iOS 16.0, *)
struct OpenSettingsIntent: AppIntent {
    static var title: LocalizedStringResource = "Open Settings"

    static var description: IntentDescription = IntentDescription("Navigate to app settings")

    static var openAppWhenRun: Bool { true }

    @MainActor
    func perform() async throws -> some IntentResult {
        // Call into Flutter via plugin
        let result = await FlutterAppIntentsPlugin.shared.handleIntentInvocation(
            identifier: "open_settings",
            parameters: [:]
        )

        if let success = result["success"] as? Bool, success {
            return .result()
        } else {
            throw IntentExecutionError.executionFailed
        }
    }
}

// MARK: - App Shortcuts Provider

@available(iOS 16.0, *)
struct AppShortcuts: AppShortcutsProvider {
    static var appShortcuts: [AppShortcut] {
        return [
            AppShortcut(
                intent: OpenProfileIntent(),
                phrases: [
                    "Open Profile with \(.applicationName)",
                    "Open Profile in \(.applicationName)",
                ],
                shortTitle: "Open Profile",
                systemImageName: "map.fill"
            ),
            AppShortcut(
                intent: OpenChatIntent(),
                phrases: [
                    "Open Chat with \(.applicationName)",
                    "Open Chat in \(.applicationName)",
                ],
                shortTitle: "Open Chat",
                systemImageName: "message.fill"
            ),
            AppShortcut(
                intent: SearchContentIntent(),
                phrases: [
                    "Search Content with \(.applicationName)",
                    "Search Content in \(.applicationName)",
                ],
                shortTitle: "Search Content",
                systemImageName: "app.fill"
            ),
            AppShortcut(
                intent: OpenSettingsIntent(),
                phrases: [
                    "Open Settings with \(.applicationName)",
                    "Open Settings in \(.applicationName)",
                ],
                shortTitle: "Open Settings",
                systemImageName: "app.fill"
            )
        ];
    }
}
