name: flutter_app_intents
description: "A Flutter plugin for integrating Apple App Intents with your iOS applications."
repository: https://github.com/cbonello/flutter_app_intents
issue_tracker: https://github.com/cbonello/flutter_app_intents/issues
homepage: https://cbonello.github.io/flutter_app_intents/
version: 0.5.0
license: MIT

environment:
  sdk: ^3.5.0
  flutter: ">=3.8.1"

dependencies:
  equatable: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^7.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterAppIntentsPlugin
        fileName: flutter_app_intents.swift
  uses-material-design: true