import 'package:flutter_app_intents/src/generator/intent_extractor.dart';

/// Generates Android AppWidgetProvider Kotlin classes for intents with results.
///
/// Creates boilerplate AppWidgetProvider classes that can display intent
/// results in widgets using RemoteViews.
///
/// For v0.8.0, this generates simple widget providers that display text
/// results.
///
/// **Important:** The generated code references Android string resources
/// that must be manually added to your app's `strings.xml` file:
/// - `@string/widget_<identifier>_loading`: Placeholder text shown before
///   result is loaded
///
/// Example:
/// ```xml
/// <string name="widget_get_weather_loading">Waiting for weather...</string>
/// ```
// TODO(enhancement): Generate string resource files automatically or make
// placeholder text configurable.
class AndroidWidgetProviderGenerator {
  /// Generates an AppWidgetProvider Kotlin class for the given intent.
  ///
  /// Returns null if the intent doesn't present results (presentsResult=false).
  ///
  /// Throws [ArgumentError] if the intent identifier is null or empty.
  String? generateProvider(
    ExtractedIntent intent, {
    required String packageName,
  }) {
    if (intent.presentsResult != true) {
      return null;
    }

    // Validate required fields
    if (intent.identifier == null || intent.identifier!.isEmpty) {
      throw ArgumentError(
        'Intent identifier must not be null or empty for widget generation',
      );
    }

    final className = _getProviderClassName(intent);
    final layoutName = _getLayoutName(intent);

    return _generateProviderCode(
      className: className,
      layoutName: layoutName,
      intentId: intent.identifier!,
      packageName: packageName,
    );
  }

  /// Generates the Kotlin code for the AppWidgetProvider.
  ///
  /// Creates a complete AppWidgetProvider class with:
  /// - onUpdate override for widget lifecycle management
  /// - updateWidget companion method for result updates (called from Flutter)
  /// - updateAppWidget private method for initial widget creation
  ///
  /// The generated code uses string resources for localization support.
  String _generateProviderCode({
    required String className,
    required String layoutName,
    required String intentId,
    required String packageName,
  }) {
    return '''
package $packageName

import android.appwidget.AppWidgetManager
import android.appwidget.AppWidgetProvider
import android.content.Context
import android.widget.RemoteViews

/**
 * AppWidgetProvider for displaying results from the $intentId intent.
 *
 * This widget is automatically generated by flutter_app_intents.
 *
 * To update the widget with results from Flutter, call:
 * ```
 * $className.updateWidget(context, appWidgetManager, appWidgetId, intentId, resultText)
 * ```
 */
class $className : AppWidgetProvider() {
    override fun onUpdate(
        context: Context,
        appWidgetManager: AppWidgetManager,
        appWidgetIds: IntArray
    ) {
        // Update all widget instances
        for (appWidgetId in appWidgetIds) {
            updateAppWidget(context, appWidgetManager, appWidgetId)
        }
    }

    companion object {
        /**
         * Updates the widget with new result text.
         *
         * This method should be called from your Flutter intent handler to update
         * the widget display with the intent result.
         *
         * @param context Android context
         * @param appWidgetManager Widget manager instance
         * @param appWidgetId ID of the widget to update
         * @param intentId The intent identifier (for validation/logging)
         * @param resultText The result text to display in the widget
         */
        fun updateWidget(
            context: Context,
            appWidgetManager: AppWidgetManager,
            appWidgetId: Int,
            intentId: String,
            resultText: String
        ) {
            // Verify this is the correct intent (optional safety check)
            if (intentId != "$intentId") {
                return
            }

            val views = RemoteViews(context.packageName, R.layout.$layoutName)
            views.setTextViewText(R.id.widget_result, resultText)
            appWidgetManager.updateAppWidget(appWidgetId, views)
        }

        /**
         * Updates the widget with the default loading text.
         *
         * Called when the widget is first created or updated through the system.
         */
        private fun updateAppWidget(
            context: Context,
            appWidgetManager: AppWidgetManager,
            appWidgetId: Int
        ) {
            val views = RemoteViews(context.packageName, R.layout.$layoutName)
            // Use string resource for localization support
            views.setTextViewText(
                R.id.widget_result,
                context.getString(R.string.widget_${intentId}_loading)
            )
            appWidgetManager.updateAppWidget(appWidgetId, views)
        }
    }
}
''';
  }

  /// Gets the provider class name for an intent.
  String _getProviderClassName(ExtractedIntent intent) {
    // Convert snake_case to PascalCase
    final parts = intent.identifier!.split('_');
    final pascalCase = parts.map(_capitalize).join();
    return '${pascalCase}WidgetProvider';
  }

  /// Gets the layout name for an intent.
  String _getLayoutName(ExtractedIntent intent) {
    return 'widget_${intent.identifier}';
  }

  /// Gets the file name for the provider class.
  String getProviderFileName(ExtractedIntent intent) {
    return '${_getProviderClassName(intent)}.kt';
  }

  /// Gets the fully qualified provider class name.
  String getProviderQualifiedName(
    ExtractedIntent intent, {
    required String packageName,
  }) {
    return '$packageName.${_getProviderClassName(intent)}';
  }

  /// Capitalizes the first letter of a string.
  String _capitalize(String s) {
    if (s.isEmpty) return s;
    return s[0].toUpperCase() + s.substring(1);
  }
}
