// ignore_for_file: cascade_invocations

import 'package:flutter_app_intents/src/generator/intent_extractor.dart';
import 'package:flutter_app_intents/src/models/intent_category.dart';

/// Generates iOS AppShortcuts.swift file for static App Shortcuts
///
/// Creates Swift code defining:
/// - AppIntent struct for each extracted intent
/// - AppShortcutsProvider implementation
/// - Siri phrases and system icons
class AppShortcutsProviderGenerator {
  /// List of non-fatal warnings from generation
  final List<String> warnings = [];

  /// Generates the complete AppShortcuts.swift file content
  ///
  /// Creates static App Shortcuts for iOS 16+. Each intent becomes an AppIntent
  /// struct that integrates with the existing FlutterAppIntentsPlugin for
  /// runtime handling.
  ///
  /// - Parameters:
  ///   - intents: List of extracted intents from Dart code
  ///   - appName: Optional app name for Siri phrases (defaults to "app")
  ///
  /// - Returns: Complete Swift source code as a string
  ///
  /// - Note: Limited to first 10 intents per iOS App Shortcuts API constraint
  String generate(List<ExtractedIntent> intents, {String? appName}) {
    warnings.clear();

    // iOS limits App Shortcuts to 10
    final limitedIntents = intents.length > 10
        ? () {
            warnings.add(
              'iOS limits App Shortcuts to 10. Only the first 10 intents will '
              'be included. Consider prioritizing your most important intents.',
            );
            return intents.take(10).toList();
          }()
        : intents;

    final buffer = StringBuffer()

      // File header
      ..writeln('//')
      ..writeln('// AppShortcuts.swift')
      ..writeln('// Generated by flutter_app_intents code generator')
      ..writeln('//')
      ..writeln('// DO NOT EDIT - This file is auto-generated')
      ..writeln('// Run: dart run flutter_app_intents:generate')
      ..writeln('//')
      ..writeln()
      ..writeln('import AppIntents')
      ..writeln('import Foundation')
      ..writeln()
      ..writeln('// MARK: - App Intent Definitions')
      ..writeln();

    // Generate each AppIntent struct
    for (final intent in limitedIntents) {
      _generateIntentStruct(buffer, intent);
      buffer.writeln();
    }

    // Generate AppShortcutsProvider
    buffer
      ..writeln('// MARK: - App Shortcuts Provider')
      ..writeln()
      ..writeln('@available(iOS 16.0, *)')
      ..writeln('struct AppShortcutsProvider: AppShortcutsProvider {')
      ..writeln('    static var appShortcuts: [AppShortcut] {');

    for (final intent in limitedIntents) {
      _generateAppShortcut(buffer, intent, appName: appName);
    }

    buffer
      ..writeln('    }')
      ..writeln('}');

    return buffer.toString();
  }

  /// Generates a single AppIntent struct definition
  void _generateIntentStruct(StringBuffer buffer, ExtractedIntent intent) {
    final structName = _intentStructName(intent.identifier!);
    final title = intent.title!;
    final description = intent.description!;
    final identifier = intent.identifier!;

    buffer
      ..writeln('@available(iOS 16.0, *)')
      ..writeln('struct $structName: AppIntent {')
      ..writeln(
        '    static var title: LocalizedStringResource = '
        '"$title"',
      )
      ..writeln()
      ..writeln('    static var description: IntentDescription = '
          'IntentDescription("$description")')
      ..writeln()
      ..writeln('    func perform() async throws -> some IntentResult {')
      ..writeln('        // Call into Flutter via plugin')
      ..writeln(
        '        let result = await '
        'FlutterAppIntentsPlugin.shared.handleIntentInvocation(',
      )
      ..writeln('            identifier: "$identifier",')
      ..writeln('            parameters: [:]')
      ..writeln('        )')
      ..writeln()
      ..writeln(
        '        if let success = result["success"] as? Bool, '
        'success {',
      )
      ..writeln(
        '            let value = result["value"] as? String ?? '
        '"Success"',
      )
      ..writeln('            return .result(value: value)')
      ..writeln('        } else {')
      ..writeln('            throw IntentExecutionError.executionFailed')
      ..writeln('        }')
      ..writeln('    }')
      ..writeln('}');
  }

  /// Generates an AppShortcut entry within the provider
  void _generateAppShortcut(
    StringBuffer buffer,
    ExtractedIntent intent, {
    String? appName,
  }) {
    final structName = _intentStructName(intent.identifier!);
    final title = intent.title!;
    final shortTitle = _generateShortTitle(title);
    final systemImage = _systemImageForCategory(intent.categoryEnum);
    final phrases = _generatePhrases(title, appName: appName);

    buffer
      ..writeln('        AppShortcut(')
      ..writeln('            intent: $structName(),')
      ..writeln('            phrases: [');
    for (final phrase in phrases) {
      buffer.writeln('                "$phrase",');
    }
    buffer
      ..writeln('            ],')
      ..writeln('            shortTitle: "$shortTitle",')
      ..writeln('            systemImageName: "$systemImage"')
      ..writeln('        )');
  }

  /// Converts intent identifier to Swift struct name
  ///
  /// Examples:
  /// - increment_counter -> IncrementCounterIntent
  /// - start_workout -> StartWorkoutIntent
  String _intentStructName(String identifier) {
    return '${identifier.split('_').map((part) => part[0].toUpperCase() + part.substring(1)).join()}Intent';
  }

  /// Generates a short title from the full title
  ///
  /// Tries to keep it concise for UI display. Max 2-3 words.
  String _generateShortTitle(String fullTitle) {
    final words = fullTitle.split(' ');
    if (words.length <= 2) {
      return fullTitle;
    }

    // Take first 2 words for short title
    return words.take(2).join(' ');
  }

  /// Generates Siri invocation phrases for an intent
  ///
  /// Creates 2-3 natural phrases users can say to invoke the intent.
  List<String> _generatePhrases(String title, {String? appName}) {
    final phrases = <String>[];

    // Primary phrase: the title itself
    phrases.add(title);

    // App-specific phrase using (.applicationName)
    // iOS replaces this with the actual app name
    phrases.add('$title in \\(.applicationName)');

    return phrases;
  }

  /// Maps IntentCategory to SF Symbol name
  ///
  /// Returns appropriate system icon for each category type.
  String _systemImageForCategory(IntentCategory category) {
    switch (category) {
      case IntentCategory.general:
        return 'app.fill';
      case IntentCategory.fitness:
        return 'figure.run';
      case IntentCategory.messaging:
        return 'message.fill';
      case IntentCategory.calling:
        return 'phone.fill';
      case IntentCategory.music:
        return 'music.note';
      case IntentCategory.video:
        return 'play.circle.fill';
      case IntentCategory.notes:
        return 'note.text';
      case IntentCategory.tasks:
        return 'checklist';
      case IntentCategory.calendar:
        return 'calendar';
      case IntentCategory.navigation:
        return 'map.fill';
      case IntentCategory.taxi:
        return 'car.fill';
      case IntentCategory.ordering:
        return 'fork.knife';
      case IntentCategory.cart:
        return 'cart.fill';
      case IntentCategory.deviceControl:
        return 'light.beacon.max.fill';
      case IntentCategory.nutrition:
        return 'fork.knife';
      case IntentCategory.timer:
        return 'timer';
      case IntentCategory.alarm:
        return 'alarm.fill';
      case IntentCategory.reminder:
        return 'bell.fill';
      case IntentCategory.weather:
        return 'cloud.sun.fill';
      case IntentCategory.news:
        return 'newspaper.fill';
    }
  }
}
