import 'package:flutter_app_intents/src/generator/app_shortcuts_provider_generator.dart';
import 'package:flutter_app_intents/src/generator/intent_extractor.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group(AppShortcutsProviderGenerator, () {
    late AppShortcutsProviderGenerator generator;

    setUp(() {
      generator = AppShortcutsProviderGenerator();
    });

    test('generates valid Swift code for single intent', () {
      final intents = [
        ExtractedIntent()
          ..identifier = 'test_action'
          ..title = 'Test Action'
          ..description = 'A test action'
          ..category = 'general',
      ];

      final swift = generator.generate(intents);

      // Check file header
      expect(swift, contains('// AppShortcuts.swift'));
      expect(
        swift,
        contains('// Generated by flutter_app_intents code generator'),
      );
      expect(swift, contains('// DO NOT EDIT - This file is auto-generated'));
      expect(swift, contains('// Run: dart run flutter_app_intents:generate'));

      // Check imports
      expect(swift, contains('import AppIntents'));
      expect(swift, contains('import Foundation'));

      // Check AppIntent struct
      expect(swift, contains('@available(iOS 16.0, *)'));
      expect(swift, contains('struct TestActionIntent: AppIntent {'));
      expect(
        swift,
        contains('static var title: LocalizedStringResource = "Test Action"'),
      );
      expect(
        swift,
        contains(
          'static var description: IntentDescription = '
          'IntentDescription("A test action")',
        ),
      );
      expect(
        swift,
        contains('func perform() async throws -> some IntentResult {'),
      );
      expect(
        swift,
        contains(
          'let result = await '
          'FlutterAppIntentsPlugin.shared.handleIntentInvocation(',
        ),
      );
      expect(swift, contains('identifier: "test_action",'));
      expect(swift, contains('parameters: [:]'));

      // Check AppShortcutsProvider
      expect(
        swift,
        contains('struct AppShortcutsProvider: AppShortcutsProvider {'),
      );
      expect(swift, contains('static var appShortcuts: [AppShortcut] {'));
      expect(swift, contains('AppShortcut('));
      expect(swift, contains('intent: TestActionIntent(),'));
      expect(swift, contains('phrases: ['));
      expect(swift, contains('"Test Action",'));
      expect(swift, contains(r'"Test Action in \(.applicationName)",'));
      expect(swift, contains('shortTitle: "Test Action",'));
      expect(swift, contains('systemImageName: "app.fill"'));
    });

    test('generates multiple AppIntent structs', () {
      final intents = [
        ExtractedIntent()
          ..identifier = 'first_action'
          ..title = 'First Action'
          ..description = 'First test'
          ..category = 'general',
        ExtractedIntent()
          ..identifier = 'second_action'
          ..title = 'Second Action'
          ..description = 'Second test'
          ..category = 'fitness',
      ];

      final swift = generator.generate(intents);

      expect(swift, contains('struct FirstActionIntent: AppIntent {'));
      expect(swift, contains('struct SecondActionIntent: AppIntent {'));
      expect(swift, contains('intent: FirstActionIntent(),'));
      expect(swift, contains('intent: SecondActionIntent(),'));
    });

    test('converts identifier to PascalCase struct name', () {
      final intents = [
        ExtractedIntent()
          ..identifier = 'start_workout'
          ..title = 'Start Workout'
          ..description = 'Starts a workout'
          ..category = 'fitness',
      ];

      final swift = generator.generate(intents);

      expect(swift, contains('struct StartWorkoutIntent: AppIntent {'));
    });

    test('generates correct SF Symbol for each category', () {
      final testCases = {
        'general': 'app.fill',
        'fitness': 'figure.run',
        'messaging': 'message.fill',
        'calling': 'phone.fill',
        'music': 'music.note',
        'video': 'play.circle.fill',
        'notes': 'note.text',
        'tasks': 'checklist',
        'calendar': 'calendar',
        'navigation': 'map.fill',
        'taxi': 'car.fill',
        'ordering': 'fork.knife',
        'cart': 'cart.fill',
        'deviceControl': 'light.beacon.max.fill',
        'nutrition': 'fork.knife',
        'timer': 'timer',
        'alarm': 'alarm.fill',
        'reminder': 'bell.fill',
        'weather': 'cloud.sun.fill',
        'news': 'newspaper.fill',
      };

      for (final entry in testCases.entries) {
        final intents = [
          ExtractedIntent()
            ..identifier = 'test'
            ..title = 'Test'
            ..description = 'Test'
            ..category = entry.key,
        ];

        final swift = generator.generate(intents);

        expect(
          swift,
          contains('systemImageName: "${entry.value}"'),
          reason: 'Category ${entry.key} should map to ${entry.value}',
        );
      }
    });

    test('generates short title from long title', () {
      final intents = [
        ExtractedIntent()
          ..identifier = 'test'
          ..title = 'Start My Daily Workout'
          ..description = 'Test'
          ..category = 'general',
      ];

      final swift = generator.generate(intents);

      // Should take first 2 words for short title
      expect(swift, contains('shortTitle: "Start My",'));
    });

    test('uses full title as short title for short titles', () {
      final intents = [
        ExtractedIntent()
          ..identifier = 'test'
          ..title = 'Start Workout'
          ..description = 'Test'
          ..category = 'general',
      ];

      final swift = generator.generate(intents);

      expect(swift, contains('shortTitle: "Start Workout",'));
    });

    test('generates Siri phrases with app name placeholder', () {
      final intents = [
        ExtractedIntent()
          ..identifier = 'test'
          ..title = 'Test Action'
          ..description = 'Test'
          ..category = 'general',
      ];

      final swift = generator.generate(intents);

      expect(swift, contains('"Test Action",'));
      expect(swift, contains(r'"Test Action in \(.applicationName)",'));
    });

    test('limits intents to 10 and generates warning', () {
      final intents = List.generate(
        15,
        (i) => ExtractedIntent()
          ..identifier = 'action_$i'
          ..title = 'Action $i'
          ..description = 'Description $i'
          ..category = 'general',
      );

      final swift = generator.generate(intents);

      // Should only generate first 10
      expect(swift, contains('struct Action0Intent: AppIntent {'));
      expect(swift, contains('struct Action9Intent: AppIntent {'));
      expect(swift, isNot(contains('struct Action10Intent: AppIntent {')));
      expect(swift, isNot(contains('struct Action14Intent: AppIntent {')));

      // Should generate warning
      expect(generator.warnings, hasLength(1));
      expect(
        generator.warnings.first,
        contains('iOS limits App Shortcuts to 10'),
      );
    });

    test('does not generate warning for 10 or fewer intents', () {
      final intents = List.generate(
        10,
        (i) => ExtractedIntent()
          ..identifier = 'action_$i'
          ..title = 'Action $i'
          ..description = 'Description $i'
          ..category = 'general',
      );

      generator.generate(intents);

      expect(generator.warnings, isEmpty);
    });

    test('clears warnings on each generate call', () {
      // Generate with 15 intents to create warning
      final manyIntents = List.generate(
        15,
        (i) => ExtractedIntent()
          ..identifier = 'action_$i'
          ..title = 'Action $i'
          ..description = 'Description $i'
          ..category = 'general',
      );

      generator.generate(manyIntents);
      expect(generator.warnings, hasLength(1));

      // Generate with 5 intents - warnings should be cleared
      final fewIntents = List.generate(
        5,
        (i) => ExtractedIntent()
          ..identifier = 'action_$i'
          ..title = 'Action $i'
          ..description = 'Description $i'
          ..category = 'general',
      );

      generator.generate(fewIntents);
      expect(generator.warnings, isEmpty);
    });

    test('handles intent with all required fields', () {
      final intents = [
        ExtractedIntent()
          ..identifier = 'complete_action'
          ..title = 'Complete Action'
          ..description = 'A complete test action'
          ..category = 'messaging',
      ];

      final swift = generator.generate(intents);

      expect(swift, contains('struct CompleteActionIntent: AppIntent {'));
      expect(
        swift,
        contains(
          'static var title: LocalizedStringResource = "Complete Action"',
        ),
      );
      expect(
        swift,
        contains(
          'static var description: IntentDescription = '
          'IntentDescription("A complete test action")',
        ),
      );
      expect(swift, contains('identifier: "complete_action",'));
      expect(swift, contains('systemImageName: "message.fill"'));
    });

    test('generates IntentExecutionError handling', () {
      final intents = [
        ExtractedIntent()
          ..identifier = 'test'
          ..title = 'Test'
          ..description = 'Test'
          ..category = 'general',
      ];

      final swift = generator.generate(intents);

      expect(
        swift,
        contains('if let success = result["success"] as? Bool, success {'),
      );
      expect(
        swift,
        contains('let value = result["value"] as? String ?? "Success"'),
      );
      expect(swift, contains('return .result(value: value)'));
      expect(swift, contains('} else {'));
      expect(swift, contains('throw IntentExecutionError.executionFailed'));
    });

    test('generates proper Swift code structure', () {
      final intents = [
        ExtractedIntent()
          ..identifier = 'test'
          ..title = 'Test'
          ..description = 'Test'
          ..category = 'general',
      ];

      final swift = generator.generate(intents);

      // Check proper indentation and structure
      expect(swift, contains('struct TestIntent: AppIntent {'));
      expect(swift, contains('    static var title:'));
      expect(swift, contains('    static var description:'));
      expect(swift, contains('    func perform() async throws'));
      expect(swift, contains('        // Call into Flutter via plugin'));
      expect(
        swift,
        contains('struct AppShortcutsProvider: AppShortcutsProvider {'),
      );
      expect(swift, contains('    static var appShortcuts: [AppShortcut] {'));
      expect(swift, contains('        AppShortcut('));
    });

    test('handles underscores in identifier correctly', () {
      final intents = [
        ExtractedIntent()
          ..identifier = 'start_my_workout_now'
          ..title = 'Start Workout'
          ..description = 'Test'
          ..category = 'fitness',
      ];

      final swift = generator.generate(intents);

      expect(swift, contains('struct StartMyWorkoutNowIntent: AppIntent {'));
      expect(swift, contains('identifier: "start_my_workout_now",'));
    });
  });
}
