// Cascade invocations would make the code generation logic less readable
// by forcing all buffer operations into cascades, reducing clarity.
// ignore_for_file: cascade_invocations

import 'package:flutter_app_intents/src/generator/shared/intent_extractor.dart';
import 'package:flutter_app_intents/src/models/intent_category.dart';

/// Generates iOS AppShortcuts.swift file for static App Shortcuts
///
/// Creates Swift code defining:
/// - AppIntent struct for each extracted intent
/// - AppShortcutsProvider implementation
/// - Siri phrases and system icons
class AppShortcutsProviderGenerator {
  /// List of non-fatal warnings from generation
  final List<String> warnings = [];

  /// Generates the complete AppShortcuts.swift file content
  ///
  /// Creates static App Shortcuts for iOS 16+. Each intent becomes an AppIntent
  /// struct that integrates with the existing FlutterAppIntentsPlugin for
  /// runtime handling.
  ///
  /// - Parameters:
  ///   - intents: List of extracted intents from Dart code
  ///   - appName: Optional app name for Siri phrases (defaults to "app")
  ///
  /// - Returns: Complete Swift source code as a string
  ///
  /// - Note: Limited to first 10 intents per iOS App Shortcuts API constraint
  String generate(List<ExtractedIntent> intents, {String? appName}) {
    warnings.clear();

    // iOS limits App Shortcuts to 10
    final limitedIntents = intents.length > 10
        ? () {
            warnings.add(
              'iOS limits App Shortcuts to 10. Only the first 10 intents will '
              'be included. Consider prioritizing your most important intents.',
            );
            return intents.take(10).toList();
          }()
        : intents;

    final buffer = StringBuffer()

      // File header
      ..writeln('//')
      ..writeln('// AppShortcuts.swift')
      ..writeln('// Generated by flutter_app_intents code generator')
      ..writeln('//')
      ..writeln('// DO NOT EDIT - This file is auto-generated')
      ..writeln('// Run: dart run flutter_app_intents:app_intents_cli')
      ..writeln('//')
      ..writeln()
      ..writeln('import AppIntents')
      ..writeln('import Foundation')
      ..writeln('import flutter_app_intents')
      ..writeln()
      ..writeln('// MARK: - Error Handling')
      ..writeln()
      ..writeln('/// Error type for App Intent execution failures')
      ..writeln('enum IntentExecutionError: Error {')
      ..writeln('    case executionFailed')
      ..writeln('}')
      ..writeln()
      ..writeln('// MARK: - App Intent Definitions')
      ..writeln();

    // Generate each AppIntent struct
    for (final intent in limitedIntents) {
      _generateIntentStruct(buffer, intent);
      buffer.writeln();
    }

    // Generate AppShortcutsProvider
    buffer
      ..writeln('// MARK: - App Shortcuts Provider')
      ..writeln()
      ..writeln('@available(iOS 16.0, *)')
      ..writeln('struct AppShortcuts: AppShortcutsProvider {')
      ..writeln('    static var appShortcuts: [AppShortcut] {')
      ..writeln('        return [');

    // Generate shortcuts and collect them as strings
    final shortcuts = <String>[];
    for (final intent in limitedIntents) {
      shortcuts.add(_generateAppShortcutString(intent, appName: appName));
    }

    // Join shortcuts with commas for clean formatting
    buffer.write(shortcuts.join(',\n'));

    buffer
      ..writeln()
      ..writeln('        ];')
      ..writeln('    }')
      ..writeln('}');

    return buffer.toString();
  }

  /// Generates a single AppIntent struct definition
  void _generateIntentStruct(StringBuffer buffer, ExtractedIntent intent) {
    final structName = _intentStructName(intent.identifier!);
    final title = intent.title!;
    final escapedTitle = _escapeSwiftString(title);
    final escapedDescription = _escapeSwiftString(intent.description!);
    final identifier = intent.identifier!;
    final escapedIdentifier = _escapeSwiftString(identifier);
    final presentsResult = intent.presentsResult ?? false;
    final params = intent.parameters;

    buffer
      ..writeln('@available(iOS 16.0, *)')
      ..writeln('struct $structName: AppIntent {')
      ..writeln(
        '    static var title: LocalizedStringResource = '
        '"$escapedTitle"',
      )
      ..writeln()
      ..writeln('    static var description: IntentDescription = '
          'IntentDescription("$escapedDescription")')
      ..writeln()
      ..writeln('    static var openAppWhenRun: Bool { true }')
      ..writeln();

    // Generate parameter properties
    for (final param in params) {
      _generateParameterProperty(buffer, param);
    }

    if (params.isNotEmpty) {
      buffer.writeln();
    }

    buffer.writeln('    @MainActor');

    // Generate different return types based on whether result is presented
    if (presentsResult) {
      buffer.writeln(
        '    func perform() async throws -> some IntentResult '
        '& ProvidesDialog {',
      );
    } else {
      buffer.writeln('    func perform() async throws -> some IntentResult {');
    }

    buffer.writeln('        // Call into Flutter via plugin');

    // Build parameters dictionary
    if (params.isEmpty) {
      buffer
        ..writeln(
          '        let result = await '
          'FlutterAppIntentsPlugin.shared.handleIntentInvocation(',
        )
        ..writeln('            identifier: "$escapedIdentifier",')
        ..writeln('            parameters: [:]')
        ..writeln('        )');
    } else {
      buffer.writeln('        var parameters: [String: Any] = [:]');
      for (final param in params) {
        if (param.isOptional) {
          // Only add optional parameters if they have a value
          buffer
            ..writeln('        if let ${param.name} = ${param.name} {')
            ..writeln('            parameters["${param.name}"] = ${param.name}')
            ..writeln('        }');
        } else {
          // Required parameters are always added
          buffer.writeln('        parameters["${param.name}"] = ${param.name}');
        }
      }
      buffer
        ..writeln()
        ..writeln(
          '        let result = await '
          'FlutterAppIntentsPlugin.shared.handleIntentInvocation(',
        )
        ..writeln('            identifier: "$escapedIdentifier",')
        ..writeln('            parameters: parameters')
        ..writeln('        )');
    }

    buffer
      ..writeln()
      ..writeln(
        '        if let success = result["success"] as? Bool, '
        'success {',
      );

    if (presentsResult) {
      // Query intent: show result in dialog
      buffer
        ..writeln(
          '            let value = result["value"] as? String ?? '
          '"Success"',
        )
        ..writeln(
          '            return .result(dialog: '
          'IntentDialog(stringLiteral: value))',
        );
    } else {
      // Action intent: just open app silently
      buffer.writeln('            return .result()');
    }

    buffer
      ..writeln('        } else {')
      ..writeln('            throw IntentExecutionError.executionFailed')
      ..writeln('        }')
      ..writeln('    }')
      ..writeln('}');
  }

  /// Generates an AppShortcut entry as a string
  String _generateAppShortcutString(
    ExtractedIntent intent, {
    String? appName,
  }) {
    final structName = _intentStructName(intent.identifier!);
    final title = intent.title!;
    final shortTitle = _escapeSwiftString(_generateShortTitle(title));
    final systemImage = _systemImageForCategory(intent.categoryEnum);
    final phrases = _generatePhrases(title, appName: appName);

    final phrasesStr = phrases
        .map((p) => '                    "${_escapeSwiftString(p)}"')
        .join(
          ',\n',
        );

    return '''
            AppShortcut(
                intent: $structName(),
                phrases: [
$phrasesStr
                ],
                shortTitle: "$shortTitle",
                systemImageName: "$systemImage"
            )''';
  }

  /// Generates a Swift property declaration for an intent parameter
  void _generateParameterProperty(
    StringBuffer buffer,
    ExtractedParameter param,
  ) {
    final swiftType = _dartTypeToSwiftType(param.type!);
    final isOptional = param.isOptional;
    final optionalMarker = isOptional ? '?' : '';

    final escapedParamTitle = _escapeSwiftString(param.title!);
    buffer.writeln('    @Parameter(title: "$escapedParamTitle")');
    buffer.writeln('    var ${param.name}: $swiftType$optionalMarker');
  }

  /// Escapes a string for use inside a Swift double-quoted string literal.
  ///
  /// Preserves Swift string interpolation sequences like `\(.applicationName)`.
  String _escapeSwiftString(String value) {
    final buffer = StringBuffer();
    for (var i = 0; i < value.length; i++) {
      final char = value[i];
      if (char == r'\') {
        // Preserve Swift interpolation: \(...)
        if (i + 1 < value.length && value[i + 1] == '(') {
          buffer.write(char);
        } else {
          buffer.write(r'\\');
        }
      } else if (char == '"') {
        buffer.write(r'\"');
      } else if (char == '\n') {
        buffer.write(r'\n');
      } else if (char == '\r') {
        buffer.write(r'\r');
      } else if (char == '\t') {
        buffer.write(r'\t');
      } else if (char == '\x00') {
        buffer.write(r'\0');
      } else {
        buffer.write(char);
      }
    }
    return buffer.toString();
  }

  /// Maps Dart parameter types to Swift types
  String _dartTypeToSwiftType(String dartType) {
    switch (dartType) {
      case 'string':
        return 'String';
      case 'integer':
        return 'Int';
      case 'boolean':
        return 'Bool';
      case 'double':
        return 'Double';
      case 'date':
        return 'Date';
      case 'url':
        return 'URL';
      default:
        return 'String'; // Fallback
    }
  }

  /// Converts intent identifier to Swift struct name
  ///
  /// Examples:
  /// - increment_counter -> IncrementCounterIntent
  /// - start_workout -> StartWorkoutIntent
  String _intentStructName(String identifier) {
    return '${identifier.split('_').where((part) => part.isNotEmpty).map(
          (part) => part[0].toUpperCase() + part.substring(1),
        ).join()}Intent';
  }

  /// Generates a short title from the full title
  ///
  /// Tries to keep it concise for UI display by intelligently selecting
  /// the most meaningful words. Skips common articles and prepositions.
  String _generateShortTitle(String fullTitle) {
    final words = fullTitle.split(' ');
    if (words.length <= 2) {
      return fullTitle;
    }

    // Expanded set of common filler words to generate more meaningful short
    // titles.
    const fillerWords = {
      'a',
      'an',
      'the',
      'in',
      'on',
      'at',
      'for',
      'to',
      'of',
      'with',
      'by',
      'is',
      'am',
      'are',
      'was',
      'were',
      'be',
      'been',
      'being',
      'have',
      'has',
      'had',
      'do',
      'does',
      'did',
      'my',
      'your',
      'his',
      'her',
      'its',
      'our',
      'their',
      'from',
      'up',
      'down',
      'out',
      'over',
      'under',
    };

    final meaningfulWords = words
        .where((word) => !fillerWords.contains(word.toLowerCase()))
        .take(2)
        .toList();

    if (meaningfulWords.isNotEmpty) {
      return meaningfulWords.join(' ');
    }

    // Fallback: use first 2 words if all words are filler words
    return words.take(2).join(' ');
  }

  /// Generates Siri invocation phrases for an intent
  ///
  /// Creates 2-3 natural phrases users can say to invoke the intent.
  /// Uses the provided appName for more specific phrases, or falls back
  /// to the generic \(.applicationName) placeholder.
  List<String> _generatePhrases(String title, {String? appName}) {
    final phrases = <String>[];

    if (appName != null && appName.isNotEmpty) {
      // Use specific app name for more natural phrases
      phrases.add('$title with $appName');
      phrases.add('$title in $appName');
      phrases.add('$title using $appName');
    } else {
      // Fallback to generic placeholder (required by iOS)
      phrases.add('$title with \\(.applicationName)');
      phrases.add('$title in \\(.applicationName)');
    }

    return phrases;
  }

  /// Maps IntentCategory to SF Symbol name
  ///
  /// Returns appropriate system icon for each category type.
  String _systemImageForCategory(IntentCategory category) {
    switch (category) {
      case IntentCategory.general:
        return 'app.fill';
      case IntentCategory.fitness:
        return 'figure.run';
      case IntentCategory.messaging:
        return 'message.fill';
      case IntentCategory.calling:
        return 'phone.fill';
      case IntentCategory.music:
        return 'music.note';
      case IntentCategory.video:
        return 'play.circle.fill';
      case IntentCategory.notes:
        return 'note.text';
      case IntentCategory.tasks:
        return 'checklist';
      case IntentCategory.calendar:
        return 'calendar';
      case IntentCategory.navigation:
        return 'map.fill';
      case IntentCategory.taxi:
        return 'car.fill';
      case IntentCategory.ordering:
        return 'fork.knife';
      case IntentCategory.cart:
        return 'cart.fill';
      case IntentCategory.deviceControl:
        return 'light.beacon.max.fill';
      case IntentCategory.nutrition:
        return 'fork.knife';
      case IntentCategory.timer:
        return 'timer';
      case IntentCategory.alarm:
        return 'alarm.fill';
      case IntentCategory.reminder:
        return 'bell.fill';
      case IntentCategory.weather:
        return 'cloud.sun.fill';
      case IntentCategory.news:
        return 'newspaper.fill';
    }
  }
}
