//
// AppShortcuts.swift
// Generated by flutter_app_intents code generator
//
// DO NOT EDIT - This file is auto-generated
// Run: dart run flutter_app_intents:app_intents_cli
//

import AppIntents
import Foundation
import flutter_app_intents

// MARK: - Error Handling

/// Error type for App Intent execution failures
enum IntentExecutionError: Error {
    case executionFailed
}

// MARK: - App Intent Definitions

@available(iOS 16.0, *)
struct IncrementCounterIntent: AppIntent {
    static var title: LocalizedStringResource = "Increment Counter"

    static var description: IntentDescription = IntentDescription("Increments the counter by one")

    static var openAppWhenRun: Bool { true }

    @MainActor
    func perform() async throws -> some IntentResult {
        // Call into Flutter via plugin
        let result = await FlutterAppIntentsPlugin.shared.handleIntentInvocation(
            identifier: "increment_counter",
            parameters: [:]
        )

        if let success = result["success"] as? Bool, success {
            return .result()
        } else {
            throw IntentExecutionError.executionFailed
        }
    }
}

@available(iOS 16.0, *)
struct ResetCounterIntent: AppIntent {
    static var title: LocalizedStringResource = "Reset Counter"

    static var description: IntentDescription = IntentDescription("Resets the counter to zero")

    static var openAppWhenRun: Bool { true }

    @MainActor
    func perform() async throws -> some IntentResult {
        // Call into Flutter via plugin
        let result = await FlutterAppIntentsPlugin.shared.handleIntentInvocation(
            identifier: "reset_counter",
            parameters: [:]
        )

        if let success = result["success"] as? Bool, success {
            return .result()
        } else {
            throw IntentExecutionError.executionFailed
        }
    }
}

@available(iOS 16.0, *)
struct GetCounterIntent: AppIntent {
    static var title: LocalizedStringResource = "Get Counter Value"

    static var description: IntentDescription = IntentDescription("Returns the current counter value")

    static var openAppWhenRun: Bool { true }

    @MainActor
    func perform() async throws -> some IntentResult & ProvidesDialog {
        // Call into Flutter via plugin
        let result = await FlutterAppIntentsPlugin.shared.handleIntentInvocation(
            identifier: "get_counter",
            parameters: [:]
        )

        if let success = result["success"] as? Bool, success {
            let value = result["value"] as? String ?? "Success"
            return .result(dialog: IntentDialog(stringLiteral: value))
        } else {
            throw IntentExecutionError.executionFailed
        }
    }
}

// MARK: - App Shortcuts Provider

@available(iOS 16.0, *)
struct AppShortcuts: AppShortcutsProvider {
    static var appShortcuts: [AppShortcut] {
        return [
            AppShortcut(
                intent: IncrementCounterIntent(),
                phrases: [
                    "Increment Counter with \(.applicationName)",
                    "Increment Counter in \(.applicationName)",
                ],
                shortTitle: "Increment Counter",
                systemImageName: "app.fill"
            ),
            AppShortcut(
                intent: ResetCounterIntent(),
                phrases: [
                    "Reset Counter with \(.applicationName)",
                    "Reset Counter in \(.applicationName)",
                ],
                shortTitle: "Reset Counter",
                systemImageName: "app.fill"
            ),
            AppShortcut(
                intent: GetCounterIntent(),
                phrases: [
                    "Get Counter Value with \(.applicationName)",
                    "Get Counter Value in \(.applicationName)",
                ],
                shortTitle: "Get Counter",
                systemImageName: "app.fill"
            )
        ];
    }
}
