//
// AppShortcuts.swift
// Generated by flutter_app_intents code generator
//
// DO NOT EDIT - This file is auto-generated
// Run: dart run flutter_app_intents:generate
//

import AppIntents
import Foundation

// MARK: - App Intent Definitions

@available(iOS 16.0, *)
struct IncrementCounterIntent: AppIntent {
    static var title: LocalizedStringResource = "Increment Counter"

    static var description: IntentDescription = IntentDescription("Increments the counter by one")

    func perform() async throws -> some IntentResult {
        // Call into Flutter via plugin
        let result = await FlutterAppIntentsPlugin.shared.handleIntentInvocation(
            identifier: "increment_counter",
            parameters: [:]
        )

        if let success = result["success"] as? Bool, success {
            let value = result["value"] as? String ?? "Success"
            return .result(value: value)
        } else {
            throw IntentExecutionError.executionFailed
        }
    }
}

@available(iOS 16.0, *)
struct ResetCounterIntent: AppIntent {
    static var title: LocalizedStringResource = "Reset Counter"

    static var description: IntentDescription = IntentDescription("Resets the counter to zero")

    func perform() async throws -> some IntentResult {
        // Call into Flutter via plugin
        let result = await FlutterAppIntentsPlugin.shared.handleIntentInvocation(
            identifier: "reset_counter",
            parameters: [:]
        )

        if let success = result["success"] as? Bool, success {
            let value = result["value"] as? String ?? "Success"
            return .result(value: value)
        } else {
            throw IntentExecutionError.executionFailed
        }
    }
}

@available(iOS 16.0, *)
struct GetCounterIntent: AppIntent {
    static var title: LocalizedStringResource = "Get Counter Value"

    static var description: IntentDescription = IntentDescription("Returns the current counter value")

    func perform() async throws -> some IntentResult {
        // Call into Flutter via plugin
        let result = await FlutterAppIntentsPlugin.shared.handleIntentInvocation(
            identifier: "get_counter",
            parameters: [:]
        )

        if let success = result["success"] as? Bool, success {
            let value = result["value"] as? String ?? "Success"
            return .result(value: value)
        } else {
            throw IntentExecutionError.executionFailed
        }
    }
}

// MARK: - App Shortcuts Provider

@available(iOS 16.0, *)
struct AppShortcutsProvider: AppShortcutsProvider {
    static var appShortcuts: [AppShortcut] {
        AppShortcut(
            intent: IncrementCounterIntent(),
            phrases: [
                "Increment Counter",
                "Increment Counter in \(.applicationName)",
            ],
            shortTitle: "Increment Counter",
            systemImageName: "app.fill"
        )
        AppShortcut(
            intent: ResetCounterIntent(),
            phrases: [
                "Reset Counter",
                "Reset Counter in \(.applicationName)",
            ],
            shortTitle: "Reset Counter",
            systemImageName: "app.fill"
        )
        AppShortcut(
            intent: GetCounterIntent(),
            phrases: [
                "Get Counter Value",
                "Get Counter Value in \(.applicationName)",
            ],
            shortTitle: "Get Counter",
            systemImageName: "app.fill"
        )
    }
}
