import 'dart:io';

import 'package:flutter/services.dart';
import 'package:flutter_app_intents/src/models/app_intent.dart';
import 'package:flutter_app_intents/src/models/app_intent_result.dart';
import 'package:flutter_app_intents/src/models/intent_donation.dart';
import 'package:flutter_app_intents/src/platform/app_intents_platform.dart';

/// Android implementation of AppIntentsPlatform
///
/// Wraps Android App Actions (Google Assistant integration) to provide
/// platform abstraction. Requires Android 7.1+ (API level 25+).
///
/// **Important:** This platform requires shortcuts.xml to be generated
/// before use. Run: `dart run flutter_app_intents:generate --platform=android`
class AndroidAppActionsPlatform extends AppIntentsPlatform {
  static const MethodChannel _channel = MethodChannel('flutter_app_intents');

  /// Store intent handlers for routing
  final Map<String, IntentHandler> _handlers = {};

  /// Whether the handler has been set up
  bool _handlerInitialized = false;

  /// Cached API level (null until first check)
  int? _apiLevel;

  /// Cached support status (null until first check)
  bool? _isSupportedCache;

  @override
  String get platformName => 'Android';

  @override
  bool get isSupported {
    // Return cached value if available
    if (_isSupportedCache != null) {
      return _isSupportedCache!;
    }

    if (!Platform.isAndroid) {
      _isSupportedCache = false;
      return false;
    }

    // Check will be performed asynchronously on first method call
    // For now, assume supported if on Android
    return true;
  }

  /// Check if the platform is supported (async version)
  ///
  /// This method queries the native Android code for the actual API level.
  Future<bool> _checkSupport() async {
    if (_isSupportedCache != null) {
      return _isSupportedCache!;
    }

    if (!Platform.isAndroid) {
      _isSupportedCache = false;
      return false;
    }

    try {
      final apiLevel = await _channel.invokeMethod<int>('getApiLevel');
      _apiLevel = apiLevel;
      _isSupportedCache = apiLevel != null && apiLevel >= 25;
      return _isSupportedCache!;
    } on PlatformException {
      // If method call fails, assume not supported
      _isSupportedCache = false;
      return false;
    }
  }

  @override
  Future<bool> registerIntent(
    AppIntent intent,
    IntentHandler handler,
  ) async {
    await _ensureSupported();

    // Store the handler
    _handlers[intent.identifier] = handler;

    // Set up global handler if first registration
    if (!_handlerInitialized) {
      _channel.setMethodCallHandler(_handleMethodCall);
      _handlerInitialized = true;
    }

    // Register with Android system
    //
    // Note: Android requires shortcuts.xml to exist before this call.
    // The shortcuts.xml file should be generated by running:
    // dart run flutter_app_intents:generate --platform=android
    try {
      final result = await _channel.invokeMethod<bool>(
        'registerIntent',
        intent.toMap(),
      );

      return result ?? false;
    } on PlatformException catch (e) {
      throw FlutterAppIntentsException(
        e.message ?? 'Registration failed',
        e.code,
      );
    }
  }

  @override
  Future<bool> registerIntents(
    List<AppIntent> intents,
    Map<String, IntentHandler> handlers,
  ) async {
    await _ensureSupported();

    // Store all handlers
    _handlers.addAll(handlers);

    // Set up global handler if first registration
    if (!_handlerInitialized) {
      _channel.setMethodCallHandler(_handleMethodCall);
      _handlerInitialized = true;
    }

    // Register with Android system
    try {
      final result = await _channel.invokeMethod<bool>(
        'registerIntents',
        {
          'intents': intents.map((i) => i.toMap()).toList(),
        },
      );

      return result ?? false;
    } on PlatformException catch (e) {
      throw FlutterAppIntentsException(
        e.message ?? 'Registration failed',
        e.code,
      );
    }
  }

  @override
  Future<bool> unregisterIntent(String identifier) async {
    await _ensureSupported();

    _handlers.remove(identifier);

    try {
      final result = await _channel.invokeMethod<bool>(
        'unregisterIntent',
        {'identifier': identifier},
      );

      return result ?? false;
    } on PlatformException catch (e) {
      throw FlutterAppIntentsException(
        e.message ?? 'Unregistration failed',
        e.code,
      );
    }
  }

  @override
  Future<List<AppIntent>> getRegisteredIntents() async {
    await _ensureSupported();

    try {
      final result = await _channel.invokeListMethod<Map<dynamic, dynamic>>(
        'getRegisteredIntents',
      );

      if (result == null) return [];

      return result
          .map((map) => AppIntent.fromMap(Map<String, dynamic>.from(map)))
          .toList();
    } on PlatformException catch (e) {
      throw FlutterAppIntentsException(
        e.message ?? 'Failed to get registered intents',
        e.code,
      );
    }
  }

  @override
  Future<bool> updateShortcuts() async {
    await _ensureSupported();

    try {
      final result = await _channel.invokeMethod<bool>('updateShortcuts');
      return result ?? false;
    } on PlatformException catch (e) {
      throw FlutterAppIntentsException(
        e.message ?? 'Failed to update shortcuts',
        e.code,
      );
    }
  }

  @override
  Future<bool> donateIntent(
    String identifier,
    Map<String, dynamic> parameters, {
    double relevanceScore = 1.0,
  }) async {
    await _ensureSupported();

    try {
      final result = await _channel.invokeMethod<bool>(
        'donateIntent',
        {
          'identifier': identifier,
          'parameters': parameters,
          'relevanceScore': relevanceScore,
        },
      );

      return result ?? false;
    } on PlatformException catch (e) {
      throw FlutterAppIntentsException(
        e.message ?? 'Failed to donate intent',
        e.code,
      );
    }
  }

  @override
  Future<bool> donateIntentBatch(
    List<IntentDonation> donations,
  ) async {
    await _ensureSupported();

    try {
      final donationMaps = donations
          .map(
            (d) => {
              'identifier': d.identifier,
              'parameters': d.parameters,
              'relevanceScore': d.relevanceScore,
              'timestamp':
                  (d.timestamp ?? DateTime.now()).millisecondsSinceEpoch,
            },
          )
          .toList();

      final result = await _channel.invokeMethod<bool>(
        'donateIntentBatch',
        {'donations': donationMaps},
      );

      return result ?? false;
    } on PlatformException catch (e) {
      throw FlutterAppIntentsException(
        e.message ?? 'Failed to donate intent batch',
        e.code,
      );
    }
  }

  /// Ensures that the platform is supported before proceeding.
  /// Throws [UnsupportedError] if not supported.
  Future<void> _ensureSupported() async {
    final supported = await _checkSupport();
    if (!supported) {
      final apiInfo = _apiLevel != null ? ' (API $_apiLevel)' : '';
      throw UnsupportedError(
        'Android App Actions require Android 7.1 (API 25) or higher$apiInfo',
      );
    }
  }

  /// Handle method calls from Android native code
  Future<dynamic> _handleMethodCall(MethodCall call) async {
    if (call.method == 'handleIntent') {
      final arguments = call.arguments as Map<Object?, Object?>?;
      if (arguments == null) {
        return AppIntentResult.failed(
          error: 'Missing intent arguments',
        ).toMap();
      }

      final identifier = arguments['identifier'] as String?;
      final parametersRaw = arguments['parameters'] as Map<Object?, Object?>?;

      if (identifier == null || parametersRaw == null) {
        return AppIntentResult.failed(
          error: 'Invalid intent arguments',
        ).toMap();
      }

      final parameters = Map<String, dynamic>.from(parametersRaw);

      try {
        final result = await _handleIntent(identifier, parameters);
        return result.toMap();
      } on Exception catch (e) {
        return AppIntentResult.failed(
          error: 'Intent handler failed: $e',
        ).toMap();
      }
    }

    return null;
  }

  /// Internal handler that routes to registered handlers
  Future<AppIntentResult> _handleIntent(
    String identifier,
    Map<String, dynamic> parameters,
  ) async {
    final handler = _handlers[identifier];
    if (handler == null) {
      return AppIntentResult.failed(
        error: 'No handler registered for intent: $identifier',
      );
    }

    try {
      return await handler(parameters);
    } on Object catch (e) {
      return AppIntentResult.failed(
        error: 'Intent handler failed: $e',
      );
    }
  }
}
