package com.example.counter_example

import android.appwidget.AppWidgetManager
import android.appwidget.AppWidgetProvider
import android.content.Context
import android.widget.RemoteViews

/**
 * AppWidgetProvider for displaying results from the get_counter intent.
 *
 * This widget is automatically generated by flutter_app_intents.
 *
 * To update the widget with results from Flutter, call:
 * ```
 * GetCounterWidgetProvider.updateWidget(context, appWidgetManager, appWidgetId, intentId, resultText)
 * ```
 */
class GetCounterWidgetProvider : AppWidgetProvider() {
    override fun onUpdate(
        context: Context,
        appWidgetManager: AppWidgetManager,
        appWidgetIds: IntArray
    ) {
        // Update all widget instances
        for (appWidgetId in appWidgetIds) {
            updateAppWidget(context, appWidgetManager, appWidgetId)
        }
    }

    companion object {
        /**
         * Updates the widget with new result text.
         *
         * This method should be called from your Flutter intent handler to update
         * the widget display with the intent result.
         *
         * @param context Android context
         * @param appWidgetManager Widget manager instance
         * @param appWidgetId ID of the widget to update
         * @param intentId The intent identifier (for validation/logging)
         * @param resultText The result text to display in the widget
         */
        fun updateWidget(
            context: Context,
            appWidgetManager: AppWidgetManager,
            appWidgetId: Int,
            intentId: String,
            resultText: String
        ) {
            // Verify this is the correct intent (optional safety check)
            if (intentId != "get_counter") {
                return
            }

            val views = RemoteViews(context.packageName, R.layout.widget_get_counter)
            views.setTextViewText(R.id.widget_result, resultText)
            appWidgetManager.updateAppWidget(appWidgetId, views)
        }

        /**
         * Initializes the widget with default content.
         *
         * Called when the widget is first created or updated through the system.
         * Sets the loading text from string resources for localization support.
         */
        private fun updateAppWidget(
            context: Context,
            appWidgetManager: AppWidgetManager,
            appWidgetId: Int
        ) {
            val views = RemoteViews(context.packageName, R.layout.widget_get_counter)
            // The layout references the loading string resource directly,
            // so we don't need to set it here. The TextView will automatically
            // display the localized loading text from strings.xml.
            appWidgetManager.updateAppWidget(appWidgetId, views)
        }
    }
}
