import 'package:flutter_app_intents/src/generator/android/resource_naming.dart';
import 'package:flutter_app_intents/src/generator/shared/intent_extractor.dart';

/// Generates Android AppWidgetProvider Kotlin classes for intents with results.
///
/// Creates boilerplate AppWidgetProvider classes that can display intent
/// results in widgets using RemoteViews.
///
/// The generated code references Android string resources
/// (`@string/widget_<identifier>_loading`) that are automatically generated
/// by [StringsGenerator]. The loading text and widget description can
/// be customized via the `widgetLoadingText()` and `widgetDescription()`
/// methods on `AppIntentBuilder`.
class WidgetProviderGenerator {
  /// Generates an AppWidgetProvider Kotlin class for the given intent.
  ///
  /// Returns null if the intent doesn't present results (presentsResult=false).
  ///
  /// Throws [ArgumentError] if the intent identifier is null or empty.
  String? generateProvider(
    ExtractedIntent intent, {
    required String packageName,
  }) {
    if (intent.presentsResult != true) {
      return null;
    }

    // Validate required fields
    if (intent.identifier == null || intent.identifier!.isEmpty) {
      throw ArgumentError(
        'Intent identifier must not be null or empty for widget generation',
      );
    }

    final className = _getProviderClassName(intent);
    final layoutName = _getLayoutName(intent);

    return _generateProviderCode(
      className: className,
      layoutName: layoutName,
      intentId: _escapeKotlinString(intent.identifier!),
      packageName: packageName,
    );
  }

  /// Generates the Kotlin code for the AppWidgetProvider.
  ///
  /// Creates a complete AppWidgetProvider class with:
  /// - onUpdate override for widget lifecycle management
  /// - updateWidget companion method for result updates (called from Flutter)
  /// - updateAppWidget private method for initial widget creation
  ///
  /// The generated code uses string resources for localization support.
  String _generateProviderCode({
    required String className,
    required String layoutName,
    required String intentId,
    required String packageName,
  }) {
    return '''
package $packageName

import android.appwidget.AppWidgetManager
import android.appwidget.AppWidgetProvider
import android.content.Context
import android.widget.RemoteViews

/**
 * AppWidgetProvider for displaying results from the $intentId intent.
 *
 * This widget is automatically generated by flutter_app_intents.
 *
 * To update the widget with results from Flutter, call:
 * ```
 * $className.updateWidget(context, appWidgetManager, appWidgetId, intentId, resultText)
 * ```
 */
class $className : AppWidgetProvider() {
    override fun onUpdate(
        context: Context,
        appWidgetManager: AppWidgetManager,
        appWidgetIds: IntArray
    ) {
        // Update all widget instances
        for (appWidgetId in appWidgetIds) {
            updateAppWidget(context, appWidgetManager, appWidgetId)
        }
    }

    companion object {
        /**
         * Updates the widget with new result text.
         *
         * This method should be called from your Flutter intent handler to update
         * the widget display with the intent result.
         *
         * @param context Android context
         * @param appWidgetManager Widget manager instance
         * @param appWidgetId ID of the widget to update
         * @param intentId The intent identifier (for validation/logging)
         * @param resultText The result text to display in the widget
         */
        fun updateWidget(
            context: Context,
            appWidgetManager: AppWidgetManager,
            appWidgetId: Int,
            intentId: String,
            resultText: String
        ) {
            // Verify this is the correct intent (optional safety check)
            if (intentId != "$intentId") {
                return
            }

            val views = RemoteViews(context.packageName, R.layout.$layoutName)
            views.setTextViewText(R.id.widget_result, resultText)
            appWidgetManager.updateAppWidget(appWidgetId, views)
        }

        /**
         * Initializes the widget with default content.
         *
         * Called when the widget is first created or updated through the system.
         * Sets the loading text from string resources for localization support.
         */
        private fun updateAppWidget(
            context: Context,
            appWidgetManager: AppWidgetManager,
            appWidgetId: Int
        ) {
            val views = RemoteViews(context.packageName, R.layout.$layoutName)
            // The layout references the loading string resource directly,
            // so we don't need to set it here. The TextView will automatically
            // display the localized loading text from strings.xml.
            appWidgetManager.updateAppWidget(appWidgetId, views)
        }
    }
}
''';
  }

  /// Gets the provider class name for an intent.
  String _getProviderClassName(ExtractedIntent intent) {
    // Convert snake_case to PascalCase
    final parts = intent.identifier!.split('_').where((p) => p.isNotEmpty);
    final pascalCase = parts.map(_capitalize).join();

    return '${pascalCase}WidgetProvider';
  }

  /// Gets the layout name for an intent.
  String _getLayoutName(ExtractedIntent intent) =>
      ResourceNaming.layoutName(intent.identifier!);

  /// Gets the file name for the provider class.
  String getProviderFileName(ExtractedIntent intent) =>
      '${_getProviderClassName(intent)}.kt';

  /// Gets the fully qualified provider class name.
  String getProviderQualifiedName(
    ExtractedIntent intent, {
    required String packageName,
  }) =>
      '$packageName.${_getProviderClassName(intent)}';

  /// Escapes a string for use inside a Kotlin double-quoted string literal.
  String _escapeKotlinString(String value) {
    return value
        .replaceAll(r'\', r'\\')
        .replaceAll('"', r'\"')
        .replaceAll('\n', r'\n')
        .replaceAll('\r', r'\r')
        .replaceAll(r'$', r'\$');
  }

  /// Capitalizes the first letter of a string.
  String _capitalize(String s) =>
      s.isEmpty ? s : s[0].toUpperCase() + s.substring(1);
}
