package com.example.weather_app_intents

import android.appwidget.AppWidgetManager
import android.appwidget.AppWidgetProvider
import android.content.Context
import android.widget.RemoteViews

/**
 * AppWidgetProvider for displaying results from the get_weather_forecast intent.
 *
 * This widget is automatically generated by flutter_app_intents.
 *
 * To update the widget with results from Flutter, call:
 * ```
 * GetWeatherForecastWidgetProvider.updateWidget(context, appWidgetManager, appWidgetId, intentId, resultText)
 * ```
 */
class GetWeatherForecastWidgetProvider : AppWidgetProvider() {
    override fun onUpdate(
        context: Context,
        appWidgetManager: AppWidgetManager,
        appWidgetIds: IntArray
    ) {
        // Update all widget instances
        for (appWidgetId in appWidgetIds) {
            updateAppWidget(context, appWidgetManager, appWidgetId)
        }
    }

    companion object {
        /**
         * Updates the widget with new result text.
         *
         * This method should be called from your Flutter intent handler to update
         * the widget display with the intent result.
         *
         * @param context Android context
         * @param appWidgetManager Widget manager instance
         * @param appWidgetId ID of the widget to update
         * @param intentId The intent identifier (for validation/logging)
         * @param resultText The result text to display in the widget
         */
        fun updateWidget(
            context: Context,
            appWidgetManager: AppWidgetManager,
            appWidgetId: Int,
            intentId: String,
            resultText: String
        ) {
            // Verify this is the correct intent (optional safety check)
            if (intentId != "get_weather_forecast") {
                return
            }

            val views = RemoteViews(context.packageName, R.layout.widget_get_weather_forecast)
            views.setTextViewText(R.id.widget_result, resultText)
            appWidgetManager.updateAppWidget(appWidgetId, views)
        }

        /**
         * Updates the widget with the default loading text.
         *
         * Called when the widget is first created or updated through the system.
         */
        private fun updateAppWidget(
            context: Context,
            appWidgetManager: AppWidgetManager,
            appWidgetId: Int
        ) {
            val views = RemoteViews(context.packageName, R.layout.widget_get_weather_forecast)
            // Use string resource for localization support
            views.setTextViewText(
                R.id.widget_result,
                context.getString(R.string.widget_get_weather_forecast_loading)
            )
            appWidgetManager.updateAppWidget(appWidgetId, views)
        }
    }
}
