//
// AppShortcuts.swift
// Generated by flutter_app_intents code generator
//
// DO NOT EDIT - This file is auto-generated
// Run: dart run flutter_app_intents:app_intents_cli
//

import AppIntents
import Foundation
import flutter_app_intents

// MARK: - Error Handling

/// Error type for App Intent execution failures
enum IntentExecutionError: Error {
    case executionFailed
}

// MARK: - App Intent Definitions

@available(iOS 16.0, *)
struct GetCurrentWeatherIntent: AppIntent {
    static var title: LocalizedStringResource = "Get Current Weather"

    static var description: IntentDescription = IntentDescription("Get current weather conditions for a location")

    static var openAppWhenRun: Bool { true }

    @Parameter(title: "Location")
    var location: String?

    @MainActor
    func perform() async throws -> some IntentResult & ProvidesDialog {
        // Call into Flutter via plugin
        var parameters: [String: Any] = [:]
        if let location = location {
            parameters["location"] = location
        }

        let result = await FlutterAppIntentsPlugin.shared.handleIntentInvocation(
            identifier: "get_current_weather",
            parameters: parameters
        )

        if let success = result["success"] as? Bool, success {
            let value = result["value"] as? String ?? "Success"
            return .result(dialog: IntentDialog(stringLiteral: value))
        } else {
            throw IntentExecutionError.executionFailed
        }
    }
}

@available(iOS 16.0, *)
struct GetTemperatureIntent: AppIntent {
    static var title: LocalizedStringResource = "Get Temperature"

    static var description: IntentDescription = IntentDescription("Get current temperature for a location")

    static var openAppWhenRun: Bool { true }

    @Parameter(title: "Location")
    var location: String?

    @MainActor
    func perform() async throws -> some IntentResult & ProvidesDialog {
        // Call into Flutter via plugin
        var parameters: [String: Any] = [:]
        if let location = location {
            parameters["location"] = location
        }

        let result = await FlutterAppIntentsPlugin.shared.handleIntentInvocation(
            identifier: "get_temperature",
            parameters: parameters
        )

        if let success = result["success"] as? Bool, success {
            let value = result["value"] as? String ?? "Success"
            return .result(dialog: IntentDialog(stringLiteral: value))
        } else {
            throw IntentExecutionError.executionFailed
        }
    }
}

@available(iOS 16.0, *)
struct GetWeatherForecastIntent: AppIntent {
    static var title: LocalizedStringResource = "Get Weather Forecast"

    static var description: IntentDescription = IntentDescription("Get weather forecast for upcoming days")

    static var openAppWhenRun: Bool { true }

    @Parameter(title: "Number of Days")
    var days: Int?
    @Parameter(title: "Location")
    var location: String?

    @MainActor
    func perform() async throws -> some IntentResult & ProvidesDialog {
        // Call into Flutter via plugin
        var parameters: [String: Any] = [:]
        if let days = days {
            parameters["days"] = days
        }
        if let location = location {
            parameters["location"] = location
        }

        let result = await FlutterAppIntentsPlugin.shared.handleIntentInvocation(
            identifier: "get_weather_forecast",
            parameters: parameters
        )

        if let success = result["success"] as? Bool, success {
            let value = result["value"] as? String ?? "Success"
            return .result(dialog: IntentDialog(stringLiteral: value))
        } else {
            throw IntentExecutionError.executionFailed
        }
    }
}

@available(iOS 16.0, *)
struct CheckRainIntent: AppIntent {
    static var title: LocalizedStringResource = "Check Rain"

    static var description: IntentDescription = IntentDescription("Check if it is currently raining at a location")

    static var openAppWhenRun: Bool { true }

    @Parameter(title: "Location")
    var location: String?

    @MainActor
    func perform() async throws -> some IntentResult & ProvidesDialog {
        // Call into Flutter via plugin
        var parameters: [String: Any] = [:]
        if let location = location {
            parameters["location"] = location
        }

        let result = await FlutterAppIntentsPlugin.shared.handleIntentInvocation(
            identifier: "check_rain",
            parameters: parameters
        )

        if let success = result["success"] as? Bool, success {
            let value = result["value"] as? String ?? "Success"
            return .result(dialog: IntentDialog(stringLiteral: value))
        } else {
            throw IntentExecutionError.executionFailed
        }
    }
}

// MARK: - App Shortcuts Provider

@available(iOS 16.0, *)
struct AppShortcuts: AppShortcutsProvider {
    static var appShortcuts: [AppShortcut] {
        return [
            AppShortcut(
                intent: GetCurrentWeatherIntent(),
                phrases: [
                    "Get Current Weather with \(.applicationName)",
                    "Get Current Weather in \(.applicationName)",
                ],
                shortTitle: "Get Current",
                systemImageName: "cloud.sun.fill"
            ),
            AppShortcut(
                intent: GetTemperatureIntent(),
                phrases: [
                    "Get Temperature with \(.applicationName)",
                    "Get Temperature in \(.applicationName)",
                ],
                shortTitle: "Get Temperature",
                systemImageName: "cloud.sun.fill"
            ),
            AppShortcut(
                intent: GetWeatherForecastIntent(),
                phrases: [
                    "Get Weather Forecast with \(.applicationName)",
                    "Get Weather Forecast in \(.applicationName)",
                ],
                shortTitle: "Get Weather",
                systemImageName: "cloud.sun.fill"
            ),
            AppShortcut(
                intent: CheckRainIntent(),
                phrases: [
                    "Check Rain with \(.applicationName)",
                    "Check Rain in \(.applicationName)",
                ],
                shortTitle: "Check Rain",
                systemImageName: "cloud.sun.fill"
            )
        ];
    }
}
